#!/usr/bin/env python3
"""
Replay simulation video from CSV files.

This script reconstructs and renders a video from simulation CSV data:
- positions_{agent_id}.csv: Agent positions and state per tick
- counters.csv: Counter tile states per tick  
- config.txt: Simulation configuration

The video is generated by initializing the game environment with the
same configuration, then updating game object states from CSV data
for each tick and rendering frames.

Can be called as:
1. Standalone script: python replay_simulation_video.py <simulation_dir>
2. From experimental_simulation.py automatically if --enable_video true

Author: Samuel Lozano
"""

import sys
import os
import csv
import argparse
from pathlib import Path
from typing import Dict, List, Any, Optional

# Add project root to path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from engine.extensions.renderer2d.renderer_2d_offline import Renderer2DOffline
from engine.interface.core_ui_module import CoreUIModule
from engine.extensions.renderer2d.renderer_ui import Renderer2DModule
from spoiled_broth.simulations.video_recorder import VideoRecorder
from spoiled_broth.rl.game_env import GameEnv


class SimulationReplay:
    """Reconstructs and renders video from simulation CSV data."""
    
    def __init__(self, simulation_dir: Path, fps: int = 24, tile_size: int = 96):
        self.simulation_dir = Path(simulation_dir)
        self.fps = fps
        self.tile_size = tile_size  # Use 96 (larger) instead of 64 for better visibility
        self.output_video = self.simulation_dir / "replay_video.mp4"
        
        # CSV paths
        self.config_path = self.simulation_dir / "config.txt"
        self.counters_csv = self.simulation_dir / "counters.csv"
        
        # Find all position CSV files
        self.position_csvs = list(self.simulation_dir.glob("positions_*.csv"))
        if not self.position_csvs:
            raise FileNotFoundError(f"No position CSV files found in {self.simulation_dir}")
        
        # Load configuration
        self.config = self._load_config()
        
        # Data structures
        self.positions_data: Dict[str, List[Dict]] = {}  # agent_id -> list of tick data
        self.counters_data: List[Dict] = []  # list of tick data
        
    def _load_config(self) -> Dict[str, Any]:
        """Load simulation configuration from config.txt."""
        config = {}
        if not self.config_path.exists():
            raise FileNotFoundError(f"Config file not found: {self.config_path}")
        
        with open(self.config_path, 'r') as f:
            for line in f:
                line = line.strip()
                if line.startswith('#') or not line or line.startswith('['):
                    continue
                # Config uses "KEY: VALUE" format, not "KEY=VALUE"
                if ': ' in line:
                    key, value = line.split(': ', 1)
                    config[key.strip()] = value.strip()
        
        return config
    
    def _load_positions(self):
        """Load all position CSV files."""
        for csv_path in self.position_csvs:
            agent_id = csv_path.stem.replace('positions_', '')
            self.positions_data[agent_id] = {}  # Use dict with tick as key
            
            with open(csv_path, 'r') as f:
                reader = csv.DictReader(f)
                for row in reader:
                    tick = int(row['frame'])
                    self.positions_data[agent_id][tick] = {
                        'tick': tick,
                        'tile_x': int(row['tile_x']),
                        'tile_y': int(row['tile_y']),
                        'pixel_x': int(row['pixel_x']),
                        'pixel_y': int(row['pixel_y']),
                        'item': row['item'],
                        'score': int(row['score'])
                    }
    
    def _load_counters(self):
        """Load counters CSV file."""
        if not self.counters_csv.exists():
            print(f"Warning: Counters CSV not found: {self.counters_csv}")
            return
        
        with open(self.counters_csv, 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                tick = int(row['frame'])
                tick_data = {'tick': tick}
                # Add all counter columns
                for key, value in row.items():
                    if key.startswith('counter_'):
                        tick_data[key] = value
                self.counters_data.append(tick_data)
    
    def _update_game_from_csv(self, env: GameEnv, tick: int):
        """Update game object states from CSV data for given tick."""
        # Update agent positions and states
        for agent_id, tick_data_dict in self.positions_data.items():
            if tick in tick_data_dict:
                tick_data = tick_data_dict[tick]
                
                # Get the agent object from game
                if agent_id in env.game.gameObjects:
                    agent_obj = env.game.gameObjects[agent_id]
                    
                    # Update position (x, y are settable; slot_x, slot_y are computed properties)
                    agent_obj.x = tick_data['pixel_x']
                    agent_obj.y = tick_data['pixel_y']
                    
                    # Update item and score
                    agent_obj.item = tick_data['item'] if tick_data['item'] else None
                    agent_obj.score = tick_data['score']
        
        # Update counter states - find the counter data for this tick
        counter_tick_data = None
        for cdata in self.counters_data:
            if cdata['tick'] == tick:
                counter_tick_data = cdata
                break
        
        if counter_tick_data:
            from spoiled_broth.world.tiles import Counter
            
            for key, value in counter_tick_data.items():
                if key.startswith('counter_'):
                    # Extract x, y from 'counter_x_y' format
                    parts = key.replace('counter_', '').split('_')
                    if len(parts) == 2:
                        x, y = int(parts[0]) - 1, int(parts[1]) - 1  # CSV uses 1-indexed
                        tile = env.game.grid.tiles[x][y]
                        if isinstance(tile, Counter):
                            tile.item = value if value else None
    
    def _serialize_game_state(self, env: GameEnv, tick: int) -> Dict:
        """Build state dict for renderer (same as simulation_runner)."""
        core_module = CoreUIModule()
        renderer_module = Renderer2DModule()
        
        state: Dict = {}
        state.update(core_module.serialize_for_agent(env.game, None, None))
        state.update(renderer_module.serialize_for_agent(env.game, None, None))
        state["tick"] = tick
        return state
    
    def generate_video(self):
        """Generate video from CSV data."""
        print(f"Loading CSV data from {self.simulation_dir}...")
        self._load_positions()
        self._load_counters()
        
        # Determine tick range from CSV data (not just count)
        all_ticks = set()
        for agent_data in self.positions_data.values():
            all_ticks.update(agent_data.keys())
        for counter_data in self.counters_data:
            all_ticks.add(counter_data['tick'])
        
        if not all_ticks:
            print("Error: No data found in CSV files")
            return
        
        ticks_to_render = sorted(list(all_ticks))
        min_tick = min(ticks_to_render)
        max_tick = max(ticks_to_render)
        
        print(f"Found {len(ticks_to_render)} ticks of data (ticks {min_tick}-{max_tick})")
        print(f"Agents: {list(self.positions_data.keys())}")
        
        # Parse configuration
        map_nr = self.config.get('MAP_NR', '')
        num_agents = int(self.config.get('NUM_AGENTS', '2'))
        game_version = self.config.get('GAME_VERSION', 'classic')
        collision_enabled = self.config.get('COLLISION_ENABLED', 'False') == 'True'
        tick_rate = float(self.config.get('TICK_RATE', '2.0'))
        tick_duration = 1.0 / tick_rate
        walking_speeds = eval(self.config.get('WALKING_SPEEDS', '{}'))
        cutting_speeds = eval(self.config.get('CUTTING_SPEEDS', '{}'))
        
        game_mode = "competition" if game_version.upper() == "COMPETITION" else "classic"
        
        # Get grid size from map file (width, height)
        map_file = self.config.get('MAP_FILE', '')
        if map_file:
            from pathlib import Path as P
            map_path = P(map_file)
            if map_path.exists():
                try:
                    with open(map_path, 'r') as f:
                        lines = [l.rstrip("\n") for l in f.readlines()]
                    if lines:
                        # grid_size = (width, height) = (len of first line, number of lines)
                        grid_size = (len(lines[0]), len(lines))
                    else:
                        grid_size = (9, 10)
                except Exception as e:
                    print(f"Warning: Could not parse map file: {e}")
                    grid_size = (9, 10)
            else:
                print(f"Warning: Map file not found: {map_file}")
                grid_size = (9, 10)
        else:
            print("Warning: No MAP_FILE in config")
            grid_size = (9, 10)
        
        print(f"\nInitializing game environment...")
        print(f"  Map: {map_nr}")
        print(f"  Mode: {game_mode} | Collision: {collision_enabled}")
        print(f"  Grid size: {grid_size}")
        print(f"  Tick duration: {tick_duration}s")
        
        # Initialize GameEnv
        env = GameEnv(
            map_nr=map_nr,
            game_mode=game_mode,
            inner_seconds=len(ticks_to_render) * tick_duration,
            grid_size=grid_size,
            walking_speeds=walking_speeds,
            cutting_speeds=cutting_speeds,
            collision_enabled=collision_enabled,
            path=str(self.simulation_dir.parent),
            enable_csv_logging=False,
        )
        env.reset()
        
        print(f"  Game initialized with agents: {env.agents}")
        
        # Determine path_root for renderer (spoiled_broth directory at project root)
        # replay_simulation_video.py is at: project/spoiled_broth/simulations/
        # spoiled_broth static assets are at: project/spoiled_broth/
        path_root = Path(__file__).parent.parent  # Go up to spoiled_broth/
        if not path_root.exists():
            print(f"Error: spoiled_broth directory not found at {path_root}")
            return
        
        # Verify sprites exist
        sprites_dir = path_root / "static" / "sprites"
        if not sprites_dir.exists():
            print(f"Error: sprites directory not found at {sprites_dir}")
            return
        
        # Initialize renderer
        print(f"\nInitializing renderer...")
        print(f"  Path root: {path_root}")
        print(f"  Tile size: {self.tile_size}")
        print(f"  FPS: {self.fps}")
        print(f"  Output: {self.output_video}")
        
        renderer = Renderer2DOffline(path_root=str(path_root), tile_size=self.tile_size)
        core_module = CoreUIModule()
        renderer_module = Renderer2DModule()
        video_recorder = VideoRecorder(self.output_video, self.fps)
        
        # Calculate frames per tick
        frames_per_tick = max(1, int(round(self.fps * tick_duration)))
        total_frames = len(ticks_to_render) * frames_per_tick
        
        print(f"  Frames per tick: {frames_per_tick}")
        print(f"  Total frames: {total_frames}")
        
        print(f"\nGenerating video...")
        prev_state = None
        
        for idx, tick in enumerate(ticks_to_render):
            if idx % 10 == 0:
                progress = (idx / len(ticks_to_render)) * 100
                print(f"  Progress: {idx}/{len(ticks_to_render)} ticks ({progress:.1f}%) - rendering tick {tick}")
            
            # Update game state from CSV data
            self._update_game_from_csv(env, tick)
            
            # Serialize current state
            curr_state = self._serialize_game_state(env, tick)
            
            if prev_state is None:
                prev_state = curr_state
            
            # Render interpolated frames for this tick
            for fi in range(frames_per_tick):
                t_interp = fi / max(1, frames_per_tick - 1) if frames_per_tick > 1 else 0.0
                frame = renderer.render_to_array(prev_state, curr_state, t_interp)
                video_recorder.write_frame_with_hud(frame, env.game)
            
            prev_state = curr_state
        
        # Finalize video
        if video_recorder.writer:
            video_recorder.writer.release()
        
        print(f"\n✓ Video generation complete!")
        print(f"  Output: {self.output_video}")
        print(f"  Duration: {len(ticks_to_render) * tick_duration:.1f}s")
        print(f"  Frames: {total_frames}")
        print(f"  Tick range: {min_tick}-{max_tick}")



def replay_from_directory(simulation_dir: str, fps: int = 24, tile_size: int = 96):
    """Helper function to replay video from simulation directory.
    
    Can be called from experimental_simulation.py after simulation completes.
    Uses larger tile_size (96) for better video visibility.
    """
    try:
        replay = SimulationReplay(Path(simulation_dir), fps=fps, tile_size=tile_size)
        replay.generate_video()
        return str(replay.output_video)
    except Exception as e:
        print(f"Error during video replay: {e}")
        import traceback
        traceback.print_exc()
        return None


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Replay simulation video from CSV files",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Generate video from simulation data  
  python replay_simulation_video.py /path/to/simulation_2026_03_11-01_38_46/
  
  # Custom FPS and tile size
  python replay_simulation_video.py /path/to/simulation/ --fps 30 --tile-size 80
"""
    )
    parser.add_argument('simulation_dir', type=str, help="Path to simulation directory")
    parser.add_argument('--fps', type=int, default=24, help="Video FPS (default: 24)")
    parser.add_argument('--tile-size', type=int, default=64, help="Tile size in pixels (default: 64)")
    
    args = parser.parse_args()
    
    simulation_dir = Path(args.simulation_dir)
    if not simulation_dir.exists():
        print(f"Error: Simulation directory not found: {simulation_dir}")
        sys.exit(1)
    
    try:
        video_path = replay_from_directory(str(simulation_dir), fps=args.fps, tile_size=args.tile_size)
        if video_path:
            print(f"\n✓ Success! Video saved to: {video_path}")
        else:
            print("\n✗ Video generation failed")
            sys.exit(1)
    except Exception as e:
        print(f"\n✗ Error during video generation: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
